### PR TITLE
Wip/sipiplus

### PR DESCRIPTION
**Pull request by Vijeinath**

### CODE REVIEW

**Comment by lrosenth** [comment]
@subotic @vijeinath All changes seem to be in new Lua code for the St.Gallen project. Didn't find changes in C++-code ;-) So the backbone is unchanged.

By the way just updated the wip/update-3rd-party-ws to reflect the newest libraries. Passes all checks.

Lukas

Am 11.06.2018 um 23:18 schrieb Ivan Subotic <notifications@github.com<mailto:notifications@github.com>>:


@subotic requested changes on this pull request.

Please add:

  *   documentation for any new features
  *   python e2e tests for any new features
  *   unit test

**Comment by subotic** [comment]
> All changes seem to be in new Lua code for the St.Gallen project. Didn't find changes in C++-code ;-) So the backbone is unchanged.

It still needs to be documented and tested.

**Comment by subotic** [comment]
I was thinking about `sipiplus` a lot. My opinion is that we should move everything related to `sipiplus` to its own repository. Likewise the custom `Knora` scripts. This `sipi` repository should only contain the core server. `Sipi` is becoming/used as an application server and the applications built with `Sipi` should live in their own repository. The analogy would be `Tomcat`. Nobody would add their application using `Tomcat` to the `Tomcat` repository.

Also, as I understand it, this is just the first part of the `SipiPlus` application. A GUI client still needs to be developed, which is probably going to be written in Angular ...

**Comment by subotic** [comment]
@Vijeinath can I delete this branch?

**Pull request closed without merging**
