### PR TITLE
fix: Compile on macOS Mojave

### LINKED ISSUE #299: Compile problems
With the latest `develop` on macOS, I get:

```
[ 76%] Linking CXX executable sipi
ld: library not found for -lidn
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I run `brew install libidn` and try again, and get:

```
[ 64%] Linking CXX executable sipi
Undefined symbols for architecture x86_64:
  "_RTMP_Alloc", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Close", referenced from:
      _rtmp_disconnect in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Connect1", referenced from:
      _rtmp_connect in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_ConnectStream", referenced from:
      _rtmp_do in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Free", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
      _rtmp_disconnect in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Init", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Read", referenced from:
      _rtmp_recv in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_SetBufferMS", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_SetupURL", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Write", referenced from:
      _rtmp_send in libcurl.a(libcurl_la-curl_rtmp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by benjamingeer**
Fixes #299.

### CODE REVIEW

**Comment by benjamingeer** [comment]
Still doesn't work:

```
Install the project...
-- Install configuration: ""
-- Installing: /Users/benjamingeer/git/Sipi/build/local/bin/sipi
CMake Error at cmake_install.cmake:175 (file):
  file INSTALL cannot find "/Users/benjamingeer/git/Sipi/local/bin/lua".


make: *** [install] Error 1
```

**Comment by subotic** [comment]
you don't need to install to run it. Just run `make` and the sipi binary can be found in the `build` folder.

Maybe there is a problem now with `make install` because I've changed the install folder into the build folder, and never thought of running `make install`.

**Comment by benjamingeer** [comment]
Do we still want to have a `make install` target? Or should I remove it?

**Comment by subotic** [comment]
@lrosenth would need to decide. For Docker we don't need it. Maybe some adventurous person would like to compile and install from source? But it only used to install locally inside the `sipi` folder, which is not really what is expected from an install target.

**Comment by subotic** [comment]
Do you need any help with this issue?

**Comment by benjamingeer** [comment]
The [Sipi docs](https://dhlab-basel.github.io/Sipi/documentation/building.html#making-a-directory-tree-for-installing-sipi) say to use `make install`, that's the only reason why I've been using it all these years.

> Do you need any help with this issue?

I just want to be able to follow the instructions under [Building Sipi from Source Code](https://dhlab-basel.github.io/Sipi/documentation/building.html) and get a working Sipi, so I can fix Sipi bugs and add new features myself.

If someone could help with that, that would be great.

**Comment by subotic** [comment]
Did you try to build inside Docker?

From inside the Sipi folder, run:
```
$ docker run -it --rm -v $PWD:/sipi dhlabbasel/sipi-base:18.04 /bin/sh -c "mkdir -p /sipi/build-linux && cd /sipi/build-linux && cmake .. && make && ctest --verbose"
```

This should always work. Building under macOS directly is not encouraged (by me at least) since this is not our deployment platform.

**Comment by benjamingeer** [comment]
> Did you try to build inside Docker?

That sounds like it's going to be a very slow development process if I have to create a Docker image every time I change one line of code in CLion.

**Comment by benjamingeer** [comment]
> this is not our deployment platform.

But this is our development platform. Unless we're going to replace all our iMacs with something else.

**Comment by subotic** [comment]
> > Did you try to build inside Docker?
> 
> That sounds like it's going to be a very slow development process if I have to create a Docker image every time I change one line of code in CLion.

No, you are building inside an existing Docker image. You are not creating a new Docker image. This is currently the only way to make sure, that everybody is building on the exactly same system.

You can always try and reinstall your mac and only use homebrew as described in the docs. Then it will probably work. You have some combination of libraries on your system installed, which doesn’t work well with building sipi.

Apparently, the build as it is defined now with CMake is not tight enough to allow building on macOS with any combination of homebrew libraries. A lot more work is needed to reach that goal. We are working on it, but it is not going to happen soon.

That is why I‘m recommending Docker. There is no need for you to waste to much of your time on making it run on macOS, since it is a moving target. When it finally works for you, it doesn’t mean that it will work for the next person.

**Comment by subotic** [comment]
Or add whatever you need. It is the same thing that you would run in the terminal.

**Comment by subotic** [comment]
> A developer needs to run the compiler every few minutes, and it needs to be as fast as possible.

Since the build directory is stored outside the Docker container, a recompile is done in matter of seconds. Only the first time will it need longer, but this is normal and the same howewer you build.

**Comment by benjamingeer** [comment]
I updated Kakadu, now I get a different build failure in Docker:

```
[ 63%] Built target project_kakadu
Scanning dependencies of target sipi
[ 64%] Building CXX object CMakeFiles/sipi.dir/src/sipi.cpp.o
In file included from /sipi/src/sipi.cpp:51:
In file included from /sipi/include/SipiImage.h:41:
In file included from /sipi/include/metadata/SipiXmp.h:31:
/sipi/local/include/exiv2/error.hpp:201:25: warning: variable templates are a C++14 extension [-Wc++14-extensions]
    class EXV_DLLPUBLIC BasicError : public AnyError {
                        ^
/sipi/local/include/exiv2/error.hpp:201:25: error: variable has incomplete type 'class EXV_DLLPUBLIC'
/sipi/local/include/exiv2/error.hpp:201:11: note: forward declaration of 'Exiv2::EXV_DLLPUBLIC'
    class EXV_DLLPUBLIC BasicError : public AnyError {
          ^
/sipi/local/include/exiv2/error.hpp:201:36: error: expected ';' at end of declaration
    class EXV_DLLPUBLIC BasicError : public AnyError {
                                   ^
                                   ;
/sipi/local/include/exiv2/error.hpp:201:38: error: expected unqualified-id
    class EXV_DLLPUBLIC BasicError : public AnyError {
                                     ^
/sipi/local/include/exiv2/error.hpp:257:13: error: C++ requires a type specifier for all declarations
    typedef BasicError<char> Error;
    ~~~~~~~ ^
/sipi/local/include/exiv2/error.hpp:257:13: error: typedef name must be an identifier
    typedef BasicError<char> Error;
            ^~~~~~~~~~~~~~~~
/sipi/local/include/exiv2/error.hpp:257:29: error: expected ';' after top level declarator
    typedef BasicError<char> Error;
                            ^
                            ;
/sipi/local/include/exiv2/error.hpp:271:22: error: qualified name refers into a specialization of variable template
      'BasicError'
    BasicError<charT>::BasicError(int code)
    ~~~~~~~~~~~~~~~~~^
/sipi/local/include/exiv2/error.hpp:201:25: note: variable template 'BasicError' declared here
    class EXV_DLLPUBLIC BasicError : public AnyError {
                        ^
In file included from /sipi/src/sipi.cpp:51:
In file included from /sipi/include/SipiImage.h:44:
In file included from /sipi/include/metadata/SipiExif.h:30:
In file included from /sipi/local/include/exiv2/exiv2.hpp:36:
In file included from /sipi/local/include/exiv2/bmpimage.hpp:34:
In file included from /sipi/local/include/exiv2/exif.hpp:35:
/sipi/local/include/exiv2/tags.hpp:221:9: error: unknown type name 'EXV_DLLLOCAL'
        EXV_DLLLOCAL virtual ExifKey* clone_() const;
        ^
/sipi/local/include/exiv2/tags.hpp:221:22: error: expected member name or ';' after declaration specifiers
        EXV_DLLLOCAL virtual ExifKey* clone_() const;
        ~~~~~~~~~~~~ ^
In file included from /sipi/src/sipi.cpp:51:
In file included from /sipi/include/SipiImage.h:44:
In file included from /sipi/include/metadata/SipiExif.h:30:
In file included from /sipi/local/include/exiv2/exiv2.hpp:50:
/sipi/local/include/exiv2/jp2image.hpp:117:9: error: unknown type name 'EXV_DLLLOCAL'
        EXV_DLLLOCAL void doWriteMetadata(BasicIo& oIo);
        ^
/sipi/local/include/exiv2/jp2image.hpp:117:22: error: expected member name or ';' after declaration specifiers
        EXV_DLLLOCAL void doWriteMetadata(BasicIo& oIo);
        ~~~~~~~~~~~~ ^
In file included from /sipi/src/sipi.cpp:51:
In file included from /sipi/include/SipiImage.h:44:
In file included from /sipi/include/metadata/SipiExif.h:30:
In file included from /sipi/local/include/exiv2/exiv2.hpp:51:
/sipi/local/include/exiv2/jpgimage.hpp:277:9: error: unknown type name 'EXV_DLLLOCAL'
        EXV_DLLLOCAL int initImage(const byte initData[], long dataSize);
        ^
/sipi/local/include/exiv2/jpgimage.hpp:277:22: error: expected member name or ';' after declaration specifiers
        EXV_DLLLOCAL int initImage(const byte initData[], long dataSize);
        ~~~~~~~~~~~~ ^
/sipi/local/include/exiv2/jpgimage.hpp:285:9: error: unknown type name 'EXV_DLLLOCAL'
        EXV_DLLLOCAL void doWriteMetadata(BasicIo& oIo);
        ^
/sipi/local/include/exiv2/jpgimage.hpp:285:22: error: expected member name or ';' after declaration specifiers
        EXV_DLLLOCAL void doWriteMetadata(BasicIo& oIo);
        ~~~~~~~~~~~~ ^
/sipi/local/include/exiv2/jpgimage.hpp:298:9: error: unknown type name 'EXV_DLLLOCAL'
        EXV_DLLLOCAL int advanceToMarker() const;
        ^
/sipi/local/include/exiv2/jpgimage.hpp:298:22: error: expected member name or ';' after declaration specifiers
        EXV_DLLLOCAL int advanceToMarker() const;
        ~~~~~~~~~~~~ ^
In file included from /sipi/src/sipi.cpp:51:
In file included from /sipi/include/SipiImage.h:44:
In file included from /sipi/include/metadata/SipiExif.h:30:
In file included from /sipi/local/include/exiv2/exiv2.hpp:55:
/sipi/local/include/exiv2/pgfimage.hpp:110:9: error: unknown type name 'EXV_DLLLOCAL'
        EXV_DLLLOCAL void doWriteMetadata(BasicIo& oIo);
        ^
/sipi/local/include/exiv2/pgfimage.hpp:110:22: error: expected member name or ';' after declaration specifiers
        EXV_DLLLOCAL void doWriteMetadata(BasicIo& oIo);
        ~~~~~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
CMakeFiles/sipi.dir/build.make:83: recipe for target 'CMakeFiles/sipi.dir/src/sipi.cpp.o' failed
make[2]: *** [CMakeFiles/sipi.dir/src/sipi.cpp.o] Error 1
CMakeFiles/Makefile2:156: recipe for target 'CMakeFiles/sipi.dir/all' failed
make[1]: *** [CMakeFiles/sipi.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
```

**Comment by benjamingeer** [comment]
Also, if I do manage to compile Sipi in Docker locally, how do I run it using the configuration in `Knora/sipi`? If I run `docker-compose up sipi` in the `Knora/sipi` directory (following the instructions in the README there), won't that download and run the a Sipi image from Dockerhub, rather than the one I've compiled locally? I think that if you want to change the build process for developers, all this needs to be explained in the Sipi and Knora docs.

**Comment by subotic** [comment]
> Also, if I do manage to compile Sipi in Docker locally, how do I run it using the configuration in `Knora/sipi`? If I run `docker-compose up sipi` in the `Knora/sipi` directory (following the instructions in the README there), won't that download and run the a Sipi image from Dockerhub, rather than the one I've compiled locally?

The `docker-compose up sipi` command works only if using a published Docker image of Sipi.

How would you start a locally compiled `sipi` with the `knora` config and scripts? Maybe we can run `sipi` inside Docker in a similar way. 

> I think that if you want to change the build process for developers, all this needs to be explained in the Sipi and Knora docs.

I agree, but we don't have a standard way of doing it. @lrosenth is using macOS, since it is easier for him. I'm using Docker since this is what we need for deployment. And you are caught in the middle. We should probably sit all together at a table, and decide on how the development pipeline should look like and then implement and document it. We can certainly have two different development pipelines, one for the DaSCH (Knora + Sipi) and one for Sipi.

**Comment by benjamingeer** [comment]
OK great, can we talk about it in Basel next week?

**Comment by subotic** [comment]
> OK great, can we talk about it in Basel next week?

Sure, gladly.

**Pull request closed without merging**
