### PR TITLE
fix: issues

### LINKED ISSUE #222: Does Sipi currently support audio files?
And if so, what should be the file format supported in order to ensure long-term archiving in Knora?

I have had a look at the CINES (cool) tool to validate a format here: https://facile.cines.fr/

And also at the KOST-CECO recommendations here [https://kost-ceco.ch/wiki/whelp/Cfa/index.php](url) but I would like to have to insight on this matter, as we have a project with a few audio files (and various formats: .m4a, .mp3).

### LINKED ISSUE #249: kakadu version outdated in documentation
In https://dhlab-basel.github.io/Sipi/documentation/building.html
Kakadu version should be corrected to v7_A_4-01727L.zip

### LINKED ISSUE #273: Https mixed content problem using sipi
When using https the info.json still contains a http link. This might be the reason why when we display our  manifests (e.g. https://ub-iiifpresentation.ub.unibas.ch/impresso/shz-1891-01-03-a-issue/manifest/) with viewers like Universalviewer or Mirador we have mixed content problems because these viewers load the info.json and use the @id for fetching high-res-images.

sipi_https_problem

### LINKED ISSUE #276: lua sqlite prepare statement not working?
Concanating the sqlite statement works:
```
db = sqlite('/home/image_resolver/db/image_resolver.db', 'RO')
qry_str = 'SELECT * FROM image_resolver WHERE image_name = "' .. identifier .. '"'
qry = db << qry_str
row = qry()
print(row)
```
but preparing the statement returns nil
```
qry = db << 'SELECT * FROM image_resolver WHERE image_name = ?'
row = qry(identifier)
```
might there be an issue with lua sqlite prepare statements or do I need another [syntax](https://dhlab-basel.github.io/Sipi/documentation/lua.html#executing-a-query)?

### LINKED ISSUE #280: Lua function SipiImage:write seems to modify its input variable if there's an error
In PR  https://github.com/dhlab-basel/Knora/pull/1191, Knora's script `upload.lua` is trying to save a `SipiImage`:

https://github.com/dhlab-basel/Knora/blob/b5f946da134311d5f966117ad91a359cfa07164b/sipi/scripts/upload.lua#L139

```lua
local jp2_file_path = config.imgroot .. '/tmp/' .. hashed_jp2_filename
local success, error_msg = uploaded_image:write(jp2_file_path)

if not success then
    send_error(500, "Unable to write " .. tostring(jp2_file_path) .. ": " .. tostring(error_msg))
return
```

This works on my local machine, but on Travis it fails in a very strange way:

https://travis-ci.org/dhlab-basel/Knora/jobs/486906660

```json
{
    "message": "Unable to write false: false"
}
```

As you can see, `jp2_file_path` has a boolean value, but I don't see how this is possible, because it was just given a string value. Could `uploaded_image:write` be modifying the value of `jp2_file_path` by mistake?

In order to figure out why the script is failing on Travis, I need the real error message from `uploaded_image:write`.

### LINKED ISSUE #284: README: binary releases
The README says:

> Freely distributable binary releases will be available soon.

Could there be a link to Dockerhub or wherever the docker images are kept?

### LINKED ISSUE #286: sqlite bug in while loop
There might be a problem using results in sqlite with prepared statements. Neither row = qry(project_name) or row = qry() in the while loop seems to return the next result
Example:
```
   db = sqlite('test.db', 'RO')
   qry = db << 'SELECT ip, access FROM access_control WHERE project = ?'
   row = qry(project_name)
   while (row) do
     print(row[0])
     row = qry(project_name)
   end
```
Thanks for checking, best
Martin

### LINKED ISSUE #287: knora.json returns empty originalMimeType
Moved from https://github.com/dhlab-basel/Knora/issues/1268.

The problem occurs with this image:

54819543-80bd2780-4c9c-11e9-8946-547d6ad3278c

To reproduce, start Sipi like this:

```
$ cd test/_test_data/
$ ../../local/bin/sipi --config config/sipi.fake-knora-test-config.lua
```

Upload the image:

```
curl -X POST -F "filename=@54819543-80bd2780-4c9c-11e9-8946-547d6ad3278c.JPG" http://localhost:1024/api/upload
```

Sipi responds with:

```json
{
   "2DwjMfOWysr-G7IrS9oZhK5.jp2": "http://localhost:1024/unit/_54819543-80bd2780-4c9c-11e9-8946-547d6ad3278c.jp2",
   "filename": "_54819543-80bd2780-4c9c-11e9-8946-547d6ad3278c.jp2"
}
```

Request `knora.json`:

```
$ curl http://localhost:1024/unit/_54819543-80bd2780-4c9c-11e9-8946-547d6ad3278c.jp2/knora.json
```

Sipi responds with:

```json
{
   "width": 373,
   "height": 496,
   "originalMimeType": "",
   "originalFilename": "32_seigneux_gabriel, Fri Jan 17, 2003,  2:05:33 PM,  8C, 7566x8822,  (288+1321), 100%, bent 6 stops,   1/8 s, R22, G2, B9\r"
}
```

### LINKED ISSUE #309: /knora.json doesn't work with a CSV file
Steps to reproduce:

1. Put a CSV file `test.csv` in `/sipi/images/tmp`.
2. Make a request to `http://localhost:1024/tmp/test.csv/knora.json`.

Sipi responds with an internal server error:

```
Internal Server Error: Sipi image error at [/sipi/src/SipiImage.cpp: 381]: Could not read file /sipi/images/tmp/test.csv
```

The Sipi log says:

```
sipi            | Sipi: ERROR IN TIFF! Module: /sipi/images/tmp/test.csv
sipi            | Sipi: Not a TIFF or MDI file, bad magic number 28755 (0x7053)
sipi            | Sipi: GET /tmp/test.csv/knora.json failed (Internal Server Error): Sipi image error at [/sipi/src/SipiImage.cpp: 381]: Could not read file /sipi/images/tmp/test.csv
```

### LINKED ISSUE #315: Any route beginning with 'test' returns a PDF file containing a test image
This caused the following problem: we changed the name of one of the Sipi test routes used in a Knora-Sipi integration test, but forgot to change the name of the route where it is called. The result was that the test called a nonexistent route. Sipi should have returned HTTP 404 (to let us know that the route does not exist), but it returned HTTP 200, because it returned the test PDF file instead.

### LINKED ISSUE #316: mimetype_consistency should also work with non-image files
Currently. this method is implemented as `SipiImage::checkMimeTypeConsistency` and works only for images. It should be made more generic so  that it also works for non-image files.

### LINKED ISSUE #321: question: controlling iiif parameters
Hi,

we are evaluating switching from iiifserver from Klokantech (https://github.com/klokantech/iiifserver) to sipi, because sipi seems far more feature complete with regards to the iiif spec. Thanks for this great software!

However, we are experiencing some issues in configuring the server to optimize the tiles that are being used when panning and zooming with an iiif compliant client like Openseadragon.

We are testing with the default configuration provided in this docker: dhlabbasel/sipi:develop
Currently, we see tiles are being upserved 1024x1024px where we would like them to be 256x256px. Also, we have no control on the zoom levels where we control when to use different 256x256px tiles.

In comparison, out-of-the box iiifserver from Klokantech, provides this info.json:
```
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "http://iiif.textus.io/Dymphna-na/",
  "protocol" : "http://iiif.io/api/image",
  "width" : 7273,
  "height" : 11520,
  "sizes" : [
     { "width" : 113, "height" : 180 },
     { "width" : 227, "height" : 360 },
     { "width" : 454, "height" : 720 }
  ],
  "tiles" : [
     { "width" : 256, "height" : 256, "scaleFactors" : [ 1, 2, 4, 8, 16, 32, 64 ] }
  ],
  "profile" : [
     "http://iiif.io/api/image/2/level1.json",
     { "formats" : [ "jpg" ],
       "qualities" : [ "native","color","gray" ],
       "supports" : ["regionByPct","regionSquare","sizeByForcedWh","sizeByWh","sizeAboveFull","rotationBy90s","mirroring"] }
  ]
}
```

Default config for sipi, provides this out-of-the-box info.json for the same source, where no info is provided about tiles, scalefactors, and the available sizes are much larger.

My question: How to change the output of this info.json files?

```
{
   "@context": "http://iiif.io/api/image/2/context.json",
   "@id": "http://sipi.textus.io/iiif/Dymphna-na",
   "protocol": "http://iiif.io/api/image",
   "width": 7273,
   "height": 11520,
   "sizes": [
      { "width": 3637, "height": 5760 },
      { "width": 1819, "height": 2880 },
      { "width": 910, "height": 1440 },
      { "width": 455, "height": 720 }
   ],
   "profile": [
      "http://iiif.io/api/image/2/level2.json",
      {
         "formats": [ "tif", "jpg", "png", "jp2", "pdf" ],
         "qualities": [ "color", "gray" ],
         "supports": [
            "color",
            "cors",
            "mirroring",
            "profileLinkHeader",
            "regionByPct",
            "regionByPx",
            "rotationArbitrary",
            "rotationBy90s",
            "sizeAboveFull",
            "sizeByWhListed",
            "sizeByForcedWh",
            "sizeByH",
            "sizeByPct",
            "sizeByW",
            "sizeByWh"
         ]
      }
   ]
}
```

Furthermore we notice that no manifest.json is provided out-of-the-box by sipi. It should be available next to the info.json, no?

Thanks for looking into this!

Kind regards,
Pieter

### PR DESCRIPTION
**Pull request by lrosenth**
This pullrequest closes the following issues:
- resolves #321
- resolves #287 
- resolves #316
- resolves #315
- resolves #309
- resolves #286
- resolves #284
- resolves #280
- resolves #276
- resolves #273
- resolves #249
- resolves #222

### CODE REVIEW

**Comment by lrosenth** [comment]
Please use my version for conficting files...

**Comment by subotic** [comment]
cool, thanks for resolving so many issues :-) a lot of work :-)

**Comment by lrosenth** [comment]
Which files are missing??

Sent from my iPad

On 3 Jul 2020, at 06:33, Ivan Subotic <notifications@github.com> wrote:

﻿

@subotic requested changes on this pull request.

Besides the failing test because of missing files, everything looks good, thanks!

**Comment by subotic** [comment]
Thanks :-)

**Pull request merged**
