### PR TITLE
Add a link to the Sipi Github repository

### PR DESCRIPTION
**Pull request by julsraemy**
As suggested in #322 by @kilchenmann

### CODE REVIEW

**Review by subotic — APPROVED** [review]

**Comment by julsraemy** [comment]
Who is authorised to merge this PR and #345? @subotic?

**Comment by subotic** [comment]
@julsraemy after review, you can do it yourself, whenever you like.

**Comment by julsraemy** [comment]
> @julsraemy after review, you can do it yourself, whenever you like.

I am not able to do it, I am not an authorised user.

**Comment by kilchenmann** [comment]
> > @julsraemy after review, you can do it yourself, whenever you like.
> 
> I am not able to do it, I am not an authorised user.

@julsraemy Hm, that's strange. Normally the whole team should have write access to the DaSCH repos.
I added you manually to the sipi developers. Now you should be able to "Squash and merge" this PR

**Comment by julsraemy** [comment]
> > > @julsraemy after review, you can do it yourself, whenever you like.
> > 
> > 
> > I am not able to do it, I am not an authorised user.
> 
> @julsraemy Hm, that's strange. Normally the whole team should have write access to the DaSCH repos.
> I added you manually to the sipi developers. Now you should be able to "Squash and merge" this PR

Thank you but the merging is still blocked on my end. 
image

**Comment by subotic** [comment]
@julsraemy can you please try again? I've made a change.

**Comment by julsraemy** [comment]
> @julsraemy can you please try again? I've made a change.

It's working. As I have just merged #345, there is still one check in progress. How long does it generally take to see the effect on https://sipi.io? Is there an additional process to be made?

**Comment by subotic** [comment]
> > @julsraemy can you please try again? I've made a change.
> 
> It's working. As I have just merged #345, there is still one check in progress. How long does it generally take to see the effect on https://sipi.io? Is there an additional process to be made?

Good question. In this repository, the publishing of the docs is not automated. You would need to run it manually after merging: `make docs-publish`.

**Comment by kilchenmann** [comment]
> > @julsraemy can you please try again? I've made a change.
> 
> It's working. As I have just merged #345, there is still one check in progress. How long does it generally take to see the effect on https://sipi.io? Is there an additional process to be made?

I think in this repo we have to publish the mkdocs manually. We should add this step to the github actions' workflow as we did in the other DSP repositories.

**Comment by julsraemy** [comment]
> > > @julsraemy can you please try again? I've made a change.
> > 
> > 
> > It's working. As I have just merged #345, there is still one check in progress. How long does it generally take to see the effect on https://sipi.io? Is there an additional process to be made?
> 
> Good question. In this repository, the publishing of the docs is not automated. You would need to run it manually after merging: `make docs-publish`.

Ok thank you.

**Comment by julsraemy** [comment]
> > > @julsraemy can you please try again? I've made a change.
> > 
> > 
> > It's working. As I have just merged #345, there is still one check in progress. How long does it generally take to see the effect on https://sipi.io? Is there an additional process to be made?
> 
> I think in this repo we have to publish the mkdocs manually. We should add this step to the github actions' workflow as we did in the other DSP repositories.

How can we achieve this for this repo?

**Pull request merged**
